### ISSUE TITLE
Assets Precompile files with Undefined variable: "$fa-css-prefix".

### ISSUE THREAD

**Issue by tomafc330** [FortAwesome/font-awesome-sass#15]
When I run the precompile task with capistrano 3 I get the follow error. Followed the way to include as per homepage. (ie. //= require font-awesome)

Version of gem: 4.0.2

```
[0m[30mDEBUG[0m [[32m9595f823[0m] [31m Undefined variable: "$fa-css-prefix".
[0m[30mDEBUG[0m [[32m9595f823[0m] [31m      (in /home/ubuntu/tmp/shared/bundle/ruby/2.0.0/gems/font-awesome-sass-4.0.2/vendor/assets/stylesheets/font-awesome/_bordered-pulled.scss)
[0m[30mDEBUG[0m [[32m9595f823[0m] [31m    /home/ubuntu/tmp/shared/bundle/ruby/2.0.0/gems/font-awesome-sass-4.0.2/vendor/assets/stylesheets/font-awesome/_bordered-pulled.scss:4
[0m[30mDEBUG[0m [[32m9595f823[0m] [31m    /home/ubuntu/tmp/shared/bundle/ruby/2.0.0/gems/sass-3.2.9/lib/sass/script/variable.rb:49:in `_perform'
[0m[30mDEBUG[0m [[32m9595f823[0m] [31m    /home/ubuntu/tmp/shared/bundle/ruby/2.0.0/gems/sass-3.2.9/lib/sass/script/node.rb:40:in `perform'
[0m[30mDEBUG[0m [[32m9595f823[0m] [31m    /home/ubuntu/tmp/shared/bundle/ruby/2.0.0/gems/sass-3.2.9/lib/sass/tree/visitors/perform.rb:398:in `block in run_interp_no_strip'
[0m[30mDEBUG[0m [[32m9595f823[0m] [31m    /home/ubuntu/tmp/shared/bundle/ruby/2.0.0/gems/sass-3.2.9/lib/sass/tree/visitors/perform.rb:396:in `map'
[0m[30mDEBUG[0m [[32m9595f823[0m] [31m    /home/ubuntu/tmp/shared/bundle/ruby/2.0.0/gems/sass-3.2.9/lib/sass/tree/visitors/perform.rb:396:in `run_interp_no_strip'
[0m[30mDEBUG[0m [[32m9595f823[0m] [31m    /home/ubuntu/tmp/shared/bundle/ruby/2.0.0/gems/sass-3.2.9/lib/sass/tree/visitors/perform.rb:406:in `run_interp'
[0m[30mDEBUG[0m [[32m9595f823[0m] [31m    /home/ubuntu/tmp/shared/bundle/ruby/2.0.0/gems/sass-3.2.9/lib/sass/tree/visitors/perform.rb:313:in `visit_rule'
[0m[30mDEBUG[0m [[32m9595f823[0m] [31m    /home/ubuntu/tmp/shared/bundle/ruby/2.0.0/gems/sass-3.2.9/lib/sass/tree/visitors/base.rb:37:in `visit'
[0m[30mDEBUG[0m [[32m9595f823[0m] [31m    /home/ubuntu/tmp/shared/bundle/ruby/2.0.0/gems/sass-3.2.9/lib/sass/tree/visitors/perform.rb:100:in `visit'
[0m[30mDEBUG[0m [[32m9595f823[0m] [31m    /home/ubuntu/tmp/shared/bundle/ruby/2.0.0/gems/sass-3.2.9/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
[0m[30mDEBUG[0m [[32m9595f823[0m] [31m    /home/ubuntu/tmp/shared/bundle/ruby/2.0.0/gems/sass-3.2.9/lib/sass/tree/visitors/base.rb:53:in `map'
[0m[30mDEBUG[0m [[32m9595f823[0m] [31m    /home/ubuntu/tmp/shared/bundle/ruby/2.0.0/gems/sass-3.2.9/lib/sass/tree/visitors/base.rb:53:in `visit_children'
[0m[30mDEBUG[0m [[32m9595f823[0m] [31m    /home/ubuntu/tmp/shared/bundle/ruby/2.0.0/gems/sass-3.2.9/lib/sass/tree/visitors/perform.rb:109:in `block in visit_children'
[0m[30mDEBUG[0m [[32m9595f823[0m] [31m    /home/ubuntu/tmp/shared/bundle/ruby/2.0.0/gems/sass-3.2.9/lib/sass/tree/visitors/perform.rb:121:in `with_environment'
[0m[30mDEBUG[0m [[32m9595f823[0m] [31m    /home/ubuntu/tmp/shared/bundle/ruby/2.0.0/gems/sass-3.2.9/lib/sass/tree/visitors/perform.rb:108:in `visit_children'
[0m[30mDEBUG[0m [[32m9595f823[0m] [31m    /home/ubuntu/tmp/shared/bundle/ruby/2.0.0/gems/sass-3.2.9/lib/sass/tree/visitors/base.rb:37:in `block in visit'
[0m[30mDEBUG[0m [[32m9595f823[0m] [31m    /home/ubuntu/tmp/shared/bundle/ruby/2.0.0/gems/sass-3.2.9/lib/sass/tree/visitors/perform.rb:128:in `visit_root'
[0m[30mDEBUG[0m [[32m9595f823[0m] [31m    /home/ubuntu/tmp/shared/bundle/ruby/2.0.0/gems/sass-3.2.9/lib/sass/tree/visitors/base.rb:37:in `visit'
[0m[30mDEBUG[0m [[32m9595f823[0m] [31m    /home/ubuntu/tmp/shared/bundle/ruby/2.0.0/gems/sass-3.2.9/lib/sass/tree/visitors/perform.rb:100:in `visit'
[0m[30mDEBUG[0m [[32m9595f823[0m] [31m    /home/ubuntu/tmp/shared/bundle/ruby/2.0.0/gems/sass-3.2.9/lib/sass/tree/visitors/perform.rb:7:in `visit'
[0m[30mDEBUG[0m [[32m9595f823[0m] [31m    /home/ubuntu/tmp/shared/bundle/ruby/2.0.0/gems/sass-3.2.9/lib/sass/tree/root_node.rb:20:in `render'
[0m[30mDEBUG[0m [[32m9595f823[0m] [31m    /home/ubuntu/tmp/shared/bundle/ruby/2.0.0/gems/sass-3.2.9/lib/sass/engine.rb:315:in `_render'
[0m[30mDEBUG[0m [[32m9595f823[0m] [31m    /home/ubuntu/tmp/shared/bundle/ruby/2.0.0/gems/sass-3.2.9/lib/sass/engine.rb:262:in `render'
```

**Comment by syedmahmad** [comment]
Hello EveryOne.
Just add these lines in your config/application.rb if you are using scss instead of css.

config.assets.precompile << %w( *.scss *.js )
