### ISSUE TITLE
assets:precompile fails for version 4.1.0

### ISSUE THREAD

**Issue by anadimisra** [FortAwesome/font-awesome-sass#36]
here's the stack trace

```
Anadis-MacBook-Pro:dev-2 anadi$ rake assets:precompile
I, [2014-06-29T16:22:53.398497 #13248]  INFO -- : Writing /Users/anadi/Code/heroku/ruchiyoga/dev-2/public/assets/tumblr-parser-75126aae2bf0d05d0e0d01dbbf905440.js
I, [2014-06-29T16:22:53.602070 #13248]  INFO -- : Writing /Users/anadi/Code/heroku/ruchiyoga/dev-2/public/assets/application-89881d5cf7391996755cfda2516b90dd.css
I, [2014-06-29T16:22:53.802326 #13248]  INFO -- : Writing /Users/anadi/Code/heroku/ruchiyoga/dev-2/public/assets/bootstrap-custom-13f53506eb1267c93cfbb74904942515.css
I, [2014-06-29T16:22:53.900598 #13248]  INFO -- : Writing /Users/anadi/Code/heroku/ruchiyoga/dev-2/public/assets/fontawesome-webfont-c9301e05ed43233a8630753f881f7578.eot
I, [2014-06-29T16:22:53.909093 #13248]  INFO -- : Writing /Users/anadi/Code/heroku/ruchiyoga/dev-2/public/assets/fontawesome-webfont-4e6f25b0cb06709f3ea8cf4faba3770e.svg
I, [2014-06-29T16:22:53.912499 #13248]  INFO -- : Writing /Users/anadi/Code/heroku/ruchiyoga/dev-2/public/assets/fontawesome-webfont-9a193766e28066d893d26bed2fa4bf78.ttf
I, [2014-06-29T16:22:53.915472 #13248]  INFO -- : Writing /Users/anadi/Code/heroku/ruchiyoga/dev-2/public/assets/fontawesome-webfont-8469702eb3d4956fcf1618b086a49ad1.woff
I, [2014-06-29T16:22:53.935085 #13248]  INFO -- : Writing /Users/anadi/Code/heroku/ruchiyoga/dev-2/public/assets/font-awesome-4cbf2bb617fe9319a5c61457f5685127.css
I, [2014-06-29T16:22:54.049134 #13248]  INFO -- : Writing /Users/anadi/Code/heroku/ruchiyoga/dev-2/public/assets/font-awesome/_bootstrap-d24fd19c6bee5787ade51e748f0be2e5.css
rake aborted!
Sass::SyntaxError: Undefined variable: "$fa-css-prefix".
  (in /Users/anadi/.rvm/gems/ruby-2.1.1/gems/font-awesome-sass-4.1.0/vendor/assets/stylesheets/font-awesome/_bordered-pulled.scss:4)
/Users/anadi/.rvm/gems/ruby-2.1.1/gems/font-awesome-sass-4.1.0/vendor/assets/stylesheets/font-awesome/_bordered-pulled.scss:4
/Users/anadi/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/script/variable.rb:49:in `_perform'
/Users/anadi/.rvm/gems/ruby-2.1.1/gems/sass-3.2.19/lib/sass/script/node.rb:40:in `perform'
```

my gem file

```
source 'https://rubygems.org'
ruby '2.1.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.1'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use the sassy bootstrap
gem 'bootstrap-sass', '~> 3.2.0.0'
# auto prefix browser specific prefixes 
gem 'autoprefixer-rails', '~> 2.0.1.20140626'
# Use official FontAwesome gem
gem 'font-awesome-sass'
# Use Uglifier as compressor for JavaScript assets
```

**Comment by tharkun24** [comment]
Hey! I've got same problem! How did you manage it?

**Comment by SurajShukla** [comment]
Hey, I am facing this issue at the moment. Any way to fix this?

**Comment by tanayuk** [comment]
Me too!

**Comment by frank0123** [comment]
Help! I had the same problem too! Here is the console info:

```
$ bundle exec rake assets:precompile RAILS_ENV=production
rake aborted!
Sass::SyntaxError: Undefined variable: "$fa-css-prefix".
(in /home/ubuntu/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/font-awesome-sass-4.3.1/assets/stylesheets/font-awesome/_animated.scss:4)
```

**Comment by MdMunam** [comment]
@frank0123  Did you ever sort this out. I am having the same issue

**Comment by odemeulder** [comment]
same problem here.
